#!/usr/bin/env python3
"""Generate the curated ZHOOR capability indexes."""

from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parent / "scripts"))
from _bootstrap import ensure_yaml

ensure_yaml()

import yaml

ROOT = Path(__file__).resolve().parent


def load_frontmatter(path: Path):
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---"):
        raise ValueError(f"{path}: missing YAML frontmatter")
    _, fm, _ = text.split("---", 2)
    return yaml.safe_load(fm) or {}


def add_entries():
    entries = []

    for path in sorted((ROOT / "skills").glob("*/SKILL.md")):
        fm = load_frontmatter(path)
        entries.append({**fm, "path": str(path.relative_to(ROOT))})

    for path in sorted((ROOT / "guidance").glob("*/GUIDANCE.md")):
        fm = load_frontmatter(path)
        entries.append({**fm, "path": str(path.relative_to(ROOT))})

    for path in sorted((ROOT / "workflows").glob("*/manifest.yaml")):
        manifest = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        entries.append({**manifest, "path": str(path.relative_to(ROOT))})

    for path in sorted((ROOT / "plugins").glob("*/manifest.yaml")):
        manifest = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        entries.append({**manifest, "path": str(path.relative_to(ROOT))})

    return sorted(entries, key=lambda item: item["id"])


def compact_source(entry):
    if entry["type"] in ("skill", "guidance"):
        source = ROOT / Path(entry["path"]).parent / "source.yaml"
        if source.exists():
            return yaml.safe_load(source.read_text(encoding="utf-8")) or {}
    return entry.get("upstream", {})


def write_catalog(entries):
    data = {"schema_version": 2, "skills": []}

    for entry in entries:
        description = (
            entry.get("description")
            or entry.get("summary")
            or f"Asset: {entry['name']}"
        )

        out = {
            key: entry.get(key)
            for key in [
                "id",
                "name",
                "display_name",
                "description",
                "type",
                "category",
                "capabilities",
                "path",
                "activation",
                "requires",
                "conflicts",
                "risk",
                "priority",
                "disable-model-invocation",
            ]
            if entry.get(key) is not None
        }

        if entry["type"] in ("workflow", "plugin"):
            out["upstream"] = entry.get("upstream", {})
            out["install"] = entry.get("install", {})
            out["summary"] = entry.get("summary", "")
            if entry.get("notes"):
                out["notes"] = entry["notes"]

        out["source"] = compact_source(entry)
        data["skills"].append(out)

    (ROOT / "catalog.yaml").write_text(
        "# Generated by build_registry.py — do not hand-edit.\n"
        + yaml.safe_dump(
            data,
            sort_keys=False,
            allow_unicode=False,
        ),
        encoding="utf-8",
    )


def write_capabilities(entries):
    lines = [
        "# ZHOOR Capability Pointers",
        "",
        "This file is intentionally compact.",
        "Use it to identify external guidance, workflows, and plugins.",
        "Do not recursively search the repository for capability discovery.",
        "",
        "| ID | Type | Capability | Runtime location |",
        "|---|---|---|---|",
    ]

    for entry in entries:
        if entry["type"] == "skill":
            continue

        runtime = ""

        if entry["type"] == "guidance":
            runtime = f"$AI_TOOLS_ROOT/guidance/{entry['id']}/"
        elif entry["type"] == "workflow":
            runtime = f"$AI_TOOLS_ROOT/workflows/{entry['id']}/"
        elif entry["type"] == "plugin":
            runtime = f"$AI_TOOLS_ROOT/plugins/{entry['id']}/"

        capabilities = ", ".join(entry.get("capabilities", []))

        lines.append(
            f"| `{entry['id']}` | `{entry['type']}` | "
            f"{capabilities} | `{runtime}` |"
        )

    lines += [
        "",
        "## Runtime rules",
        "",
        "- `skill`: loaded by the Agent Skills mechanism.",
        "- `guidance`: task-selected reference material; load only when relevant.",
        "- `workflow`: external development system; inspect its manifest and runtime command.",
        "- `plugin`: external integration; inspect its manifest and runtime installation.",
        "- Never confuse registration with installation.",
    ]

    (ROOT / "capabilities.md").write_text(
        "\n".join(lines) + "\n",
        encoding="utf-8",
    )


def write_guidance_index(entries):
    lines = [
        "# ZHOOR Guidance Index",
        "",
        "Guidance is selected automatically when its task triggers match.",
        "Do not load all guidance by default.",
        "",
        "| Guidance | Trigger | Path |",
        "|---|---|---|",
    ]

    for entry in entries:
        if entry["type"] != "guidance":
            continue

        trigger = ", ".join(entry.get("capabilities", []))
        lines.append(
            f"| `{entry['id']}` | {trigger} | "
            f"`{entry['path']}` |"
        )

    (ROOT / "guidance" / "INDEX.md").write_text(
        "\n".join(lines) + "\n",
        encoding="utf-8",
    )


def write_index(entries):
    categories = {}
    for entry in entries:
        categories.setdefault(entry["category"], []).append(entry)

    lines = [
        "# my-ai-skills registry index",
        "",
        "Read this compact routing index before non-trivial work.",
        "Do not load every asset.",
        "",
        "## Rules",
        "",
        "1. Match the task to a category first.",
        "2. Load only the smallest relevant skill set.",
        "3. `explicit` / `manual` skills are never inferred unless requested.",
        "4. `contextual` capabilities may be selected when the task clearly matches.",
        "5. `skill-router` is the only always-on routing skill.",
        "6. Guidance, workflows, and plugins are capability pointers, not skill prompts.",
        "7. Use `capabilities.md` for non-skill capability lookup.",
        "8. Never recursively search the repository for routine capability discovery.",
        "",
        "## Categories",
        "",
    ]

    for category in sorted(categories):
        title = category.replace("-", " ").title()
        lines.append(f"- **{title}** → `categories/{category}.md`")

    lines += [
        "",
        "## Capability layer",
        "",
        "Use `capabilities.md` for guidance, workflow, and plugin routing.",
        "Use `$AI_TOOLS_ROOT/guidance/INDEX.md` for coding/task guidance.",
        "",
        "## Agent Skills integration",
        "",
        "Skills use standard `SKILL.md` metadata and are installed into the "
        "Agent Skills compatible global locations.",
        "",
        "## Runtime",
        "",
        "`$AI_TOOLS_ROOT` is the durable local AI-tools root.",
        "Skills: `$AI_TOOLS_ROOT/skills/installed/`",
        "Guidance: `$AI_TOOLS_ROOT/guidance/`",
        "Workflows: `$AI_TOOLS_ROOT/workflows/`",
        "Plugins: `$AI_TOOLS_ROOT/plugins/`",
    ]

    (ROOT / "INDEX.md").write_text(
        "\n".join(lines) + "\n",
        encoding="utf-8",
    )

    catdir = ROOT / "categories"
    catdir.mkdir(exist_ok=True)

    for category, category_entries in categories.items():
        lines = [
            f"# {category.replace('-', ' ').title()}",
            "",
            "| Asset | Type | Activation | Capabilities | Description |",
            "|---|---|---|---|---|",
        ]

        for entry in sorted(category_entries, key=lambda item: item["id"]):
            asset_type = entry["type"]

            if asset_type == "skill":
                link = f"../skills/{entry['id']}/SKILL.md"
            elif asset_type == "guidance":
                link = f"../guidance/{entry['id']}/GUIDANCE.md"
            elif asset_type == "workflow":
                link = f"../workflows/{entry['id']}/manifest.yaml"
            else:
                link = f"../plugins/{entry['id']}/manifest.yaml"

            lines.append(
                f"| [{entry['id']}]({link}) | {asset_type} | "
                f"{entry.get('activation', '')} | "
                f"{', '.join(entry.get('capabilities', []))} | "
                f"{entry.get('description') or entry.get('summary', '')} |"
            )

        (catdir / f"{category}.md").write_text(
            "\n".join(lines) + "\n",
            encoding="utf-8",
        )


def main():
    entries = add_entries()
    write_catalog(entries)
    write_index(entries)
    write_capabilities(entries)
    write_guidance_index(entries)
    print(f"Generated registry for {len(entries)} assets.")


if __name__ == "__main__":
    main()
